language: generic

branches:
  except: # skip release tags
    - /^v?\d+\.\d+(\.\d+)?(-\S*)?$/

_shared_job: &SHARED_JOB
  install:
    - curl --silent --output terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_${TF_OS}.zip
    - sha256sum terraform.zip  | grep ${TF_SHA256}
    - unzip terraform.zip ; rm -f terraform.zip; chmod +x terraform
    - mkdir -p ${HOME}/bin ; export PATH=${PATH}:${HOME}/bin; mv terraform ${HOME}/bin/
    - terraform -v
  script:
    - terraform fmt -check -diff aws-budget/
    - terraform fmt -check -diff datadog-budget/
    - terraform init tests/
    - terraform validate tests/

jobs:
  include:
    - stage: Validate
      env:
        - TF_VERSION=0.12.24
        - TF_OS=linux_amd64
        - TF_SHA256=602d2529aafdaa0f605c06adb7c72cfb585d8aa19b3f4d8d189b42589e27bf11
      <<: *SHARED_JOB
    # - env:
    #     - TF_VERSION=0.12.23
    #     - TF_OS=linux_amd64
    #     - TF_SHA256=78fd53c0fffd657ee0ab5decac604b0dea2e6c0d4199a9f27db53f081d831a45
    #   <<: *SHARED_JOB
    - stage: Release
      if: branch = master AND (type = push OR type = api)
      language: node
      node_js: 12
      install: ignore
      script: ignore
      env:
        - secure: "I61I5GajRB1RtKNZkt+WkUHVTjfVhlDCBEQKjhIv9cQ8Jni0fJUmiWIZbCiOsaUVGCd49wPJCewHSJ/r2IzaS+oBbiT2cs8mspuEOLiepAFrb19W2j60Z0woEIUPjGjHO/BW3PiQDXGalzyacxSjkqPcLQq0npAByGTyJyGIAZbFcvSTxf32YI0WU6KduELUb64jUGK33s+DLW1gIR6zt8U1ABNGxmJ3sgiS4RCZy/wLDD91DdbffXXXNQEFmSlaz+VVXu83J7gx932g9COxN5HlmN2Gv/z4gFX4UNdYrA+1U8WoL3eBxTjpr470hYtKDfdIfS/pG9AOkI/KhKtzxP79ai5rqrx8P26tiqtFDqMODcGnKQLyw6KYaM8goBx+qRuTXVGZOJaRW6fxkvOjd6oLRVcZjlu0NHNSKo4lyBtiwSRTyGZgZXp1P84FrGUl8HQMVFx6L4o8ei0dVz1NDbmgjDiVglquarvEqcD4ebHcw41E5JXbGLfk90CzrKSf/4opREYLWLUuyBBZv2V9SMVPqkiAXuyH8YxOkb2GQs27h+w00b5+tqV7WBX7+GUaOHIHzqs69tDplqnuJQXVA/02sbSfqXDawPlSg0Orgt5QjnZQ+FkCOxANC1A/fIwn4f1Vboq+CSWhOuiK/OQI+Mwa5I2FB7kwscjTKgq4xhg="
      deploy:
        - provider: script
          script: npx semantic-release
