name: Test Pull Request

on:
  pull_request:
    

jobs:
  test:
    name: Test PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.2
      - name: Terraform Format aws-budget
        working-directory: aws-budget/
        run: terraform fmt -check -diff
      - name: Terraform Format datadog-budget
        working-directory: datadog-budget/
        run: terraform fmt -check -diff
      - name: Terraform Test
        working-directory: tests/
        run: terraform init
      - name: Terraform Validate
        working-directory: tests/
        run: terraform validate